# Generated by Django 4.1 on 2024-12-28 19:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backDev', '0004_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='year_images/')),
                ('table', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
